# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 4
name = "Institucional"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Institucional"
name = "Sobre nós"
url = "/sobre-nos"
pre = "<i class='dropdown-icon text-primary fas fa-home'></i>"
post = "<small class='dropdown-subtitle'>Conheça a nossa história.</small>"
weight = 1

[[main]]
parent = "Institucional"
name = "Nossas certificações"
url = "/certificacoes"
pre = "<i class='dropdown-icon text-primary fas fa-medal'></i>"
post = "<small class='dropdown-subtitle'>Veja nossas certificações.</small>"
weight = 2

[[main]]
parent = "Institucional"
name = "Perfil de parceiro"
url = "https://cloud.google.com/find-a-partner/partner/funccloud"
pre = "<i class='dropdown-icon text-primary fas fa-tasks'></i>"
post = "<small class='dropdown-subtitle'>Acesse nosso perfil de parceiro do Google.</small>"
weight = 3


[[main]]
weight = 6
name = "Produtos"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Produtos"
name = "Google Workspace"
pre = "<i class='dropdown-icon text-primary fab fa-google'></i>"
post = "<small class='dropdown-subtitle'>Extraia o máximo do Google Workspace conosco.</small>"
url = "/produtos/google-workspace"
weight = 1

[[main]]
parent = "Produtos"
name = "Google Cloud"
pre = "<i class='dropdown-icon text-primary fas fa-cloud'></i>"
post = "<small class='dropdown-subtitle'>Extraia o máximo do Google Cloud conosco.</small>"
url = "/produtos/google-cloud"
weight = 2

[[main]]
parent = "Produtos"
name = "Professional services"
pre = "<i class='dropdown-icon text-primary fas fa-code'></i>"
post = "<small class='dropdown-subtitle'>Serviços personalizados para sua empresa.</small>"
url = "/produtos/professional-services"
weight = 3

[[main]]
parent = "Produtos"
name = "Ver todos"
pre = "<i class='dropdown-icon text-primary fas fa-arrow-right'></i>"
url = "/produtos"
weight = 4

[[main]]
name = "Materiais"
weight = 10
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Materiais"
name = "Blog"
pre = "<i class='dropdown-icon text-primary fas fa-newspaper'></i>"
post = "<small class='dropdown-subtitle'>Leia nosso conteúdo.</small>"
url = "/blog"
weight = 1

[[main]]
parent = "Materiais"
name = "Guia de inovação"
pre = "<i class='dropdown-icon text-primary fas fa-lightbulb'></i>"
post = "<small class='dropdown-subtitle'>Veja o material.</small>"
url = "https://7135940387210439462.partnermarketingstudio.com/guia-de-inovacao"
weight = 2

[[main]]
parent = "Materiais"
name = "O futuro da IA"
pre = "<i class='dropdown-icon text-primary fas fa-brain'></i>"
post = "<small class='dropdown-subtitle'>Veja o material.</small>"
url = "https://7135940387210439462.partnermarketingstudio.com/o-futuro-da-ia"
weight = 3


[[main]]
name = "Contato"
url = "/contato"
weight = 30

# footer menu left
[[footer_left]]
name = "Sobre nós"
url = "/sobre-nos"
weight = 1

[[footer_left]]
name = "Nossas certificações"
url = "/certificacoes"
weight = 2

[[footer_left]]
name = "Perfil de parceiro do Google"
url = "https://cloud.google.com/find-a-partner/partner/funccloud"
weight = 3


# footer menu middle
[[footer_middle]]
name = "Google Cloud"
url = "/produtos/google-cloud/"
weight = 1

[[footer_middle]]
name = "Professional services"
url = "/produtos/professional-services"
weight = 2

[[footer_middle]]
name = "Ver todos"
url = "/produtos"
weight = 3

# footer menu right
[[footer_right]]
name = "Blog"
url = "/blog"
weight = 1

[[footer_right]]
name = "Contato"
url = "/contato"
weight = 2

[[footer_right]]
name = "Suporte"
url = "mailto:suporte@funccloud.com"
weight = 3
