# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 4
name = "Institucional"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Institucional"
name = "Sobre nós"
url = "/sobre-nos"
pre = "<i class='dropdown-icon fas fa-home'></i>"
post = "<small class='dropdown-subtitle'>Conheça a nossa história.</small>"
weight = 1

[[main]]
parent = "Institucional"
name = "Nossas certificações"
url = "/certificacoes"
pre = "<i class='dropdown-icon fas fa-medal'></i>"
post = "<small class='dropdown-subtitle'>Veja nossas certificações</small>"
weight = 2

[[main]]
parent = "Institucional"
name = "Perfil de parceiro"
url = "https://cloud.google.com/find-a-partner/partner/funccloud"
pre = "<i class='dropdown-icon fas fa-tasks'></i>"
post = "<small class='dropdown-subtitle'>Acesse nosso perfil de parceiro do Google</small>"
weight = 3


[[main]]
weight = 6
name = "Products"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Products"
name = "CRM"
pre = "<i class='dropdown-icon fas fa-users'></i>"
post = "<small class='dropdown-subtitle'>Convert leads and close sales deals faster.</small>"
url = "products/product-1/"
weight = 1

[[main]]
parent = "Products"
name = "Help Desk"
pre = "<i class='dropdown-icon fas fa-dice-d6'></i>"
post = "<small class='dropdown-subtitle'>Software to deliver great customer support.</small>"
url = "products/product-2/"
weight = 2

[[main]]
parent = "Products"
name = "Workplace"
pre = "<i class='dropdown-icon fas fa-laptop-house'></i>"
post = "<small class='dropdown-subtitle'>Application built to improve productivity.</small>"
url = "products/product-3/"
weight = 3

[[main]]
parent = "Products"
name = "Analytics"
pre = "<i class='dropdown-icon fas fa-chart-bar'></i>"
post = "<small class='dropdown-subtitle'>Create custom reports from any data set.</small>"
url = "products/product-4/"
weight = 4

[[main]]
parent = "Products"
name = "View All Product"
pre = "<i class='dropdown-icon text-primary fas fa-arrow-right'></i>"
url = "products/"
weight = 5

[[main]]
weight = 13
name = "Blog"
hasChildren = true

[[main]]
parent = "Blog"
name = "Blog Posts"
url = "blog/"
weight = 3

[[main]]
parent = "Blog"
name = "Blog Details"
url = "blog/post-1/"
weight = 8

[[main]]
parent = "Blog"
name = "Author"
url = "author/"
weight = 11

[[main]]
parent = "Blog"
name = "Author Details"
url = "author/awab-husameldin/"
weight = 12

[[main]]
weight = 15
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Pricing"
url = "pricing/"
weight = 1

[[main]]
parent = "Pages"
name = "Case Studies"
url = "case-studies/"
weight = 4

[[main]]
parent = "Pages"
name = "Case Studies Details"
url = "case-studies/case-1/"
weight = 5

[[main]]
parent = "Pages"
name = "Contact"
url = "contact/"
weight = 10

[[main]]
parent = "Pages"
name = "FAQ"
url = "faq/"
weight = 16

[[main]]
parent = "Pages"
name = "Privacy Policy"
url = "privacy-policy/"
weight = 20

[[main]]
parent = "Pages"
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 24

[[main]]
name = "Contato"
url = "/contato"
weight = 30

# footer menu left
[[footer_left]]
name = "Sobre nós"
url = "/sobre-nos"
weight = 1

[[footer_left]]
name = "Nossas certificações"
url = "/certificacoes"
weight = 2

[[footer_left]]
name = "Perfil de parceiro do Google"
url = "https://cloud.google.com/find-a-partner/partner/funccloud"
weight = 3


# footer menu middle
[[footer_middle]]
name = "CRM"
url = "products/product-1/"
weight = 1

[[footer_middle]]
name = "Help Desk"
url = "products/product-2/"
weight = 2

[[footer_middle]]
name = "Workplace"
url = "products/product-3/"
weight = 3

[[footer_middle]]
name = "Analytics"
url = "products/product-4/"
weight = 4

# footer menu right
[[footer_right]]
name = "FAQ"
url = "faq/"
weight = 1

[[footer_right]]
name = "Contact"
url = "contact/"
weight = 2

[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 4
