[build]
command = "ng run funccloud.com:collect-vars && ng build --configuration production"
publish = "dist/funccloud.com/browser"
[[plugins]]
package = "@netlify/plugin-emails"
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
